# Test against the latest version of this Node.js version
environment:
  nodejs_version: 6

# Install scripts. (runs after repo cloning)
install:
  - ps: >-
    # Get the latest stable version of Node.js or io.js
    Install-Product node $env:nodejs_version
    # install modules
    npm install --loglevel=error
    # Creates the .npmrc file on the AppVeyor CI server.
    "//registry.npmjs.org/:_authToken=$env:npm_auth_token`n" | out-file "$env:userprofile\.npmrc" -Encoding ASCII

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - npm test

# Build project
build:
  - npm run build qeditor

# Cache node_modules for next builds
cache:
  - node_modules -> package.json
  - '%APPDATA%\npm-cache'

# Deploy package
deploy_script:
  - ps: npm publish "dist/qeditor"
